### ISSUE TITLE
Замечания по lw2/task2

### ISSUE THREAD

**Issue by ivklgn** [lifelsbeautiful/web-development-course#2]
исходный код 1ой лабы поместите в папку lw1 чтобы не было путаницы

**Comment by ivklgn** [comment]
```html
      <button class="button button-large standart">XLarge Default</button>
      <button class="button button-large filled">XLarge Default</button>
      <button class="button button-large rounded">XLarge Default</button>
      <button class="button button-large rounded filled">XLarge Default</button>
      <button class="button button-large oval">XLarge Default</button>
      <button class="button button-large oval filled">XLarge Default</button>
```

добочные классы standart, filled и другие - не по заданию. filled -> button-filled. и так далее

**Comment by ivklgn** [comment]
по заданию не должно быть классов standart, oval. перепроверьте имена по заданию

**Comment by ivklgn** [comment]
```html
  <div class="button">
    <div class="button-large">
``` 

классы кнопок не должны использоваться для вне кнопок. если хотите сделать блочные flexbox контейнеры для выравнивания набора кнопок - используйте другие имена, например: 

```html
<div class="buttons-demo">
  <div class="buttons-large-demo">
    <button>...</button>
    <button>...</button>
    <button>...</button>
  </div>
  ...
</div>
```

--------

проблема осталась

```html
    <div class="button-medium">
      <button class="button button-medium ">Medium info</button>
      <button class="button button-medium-filled ">Medium info</button>
      <button class="button button-medium button-rounded">Medium info</button>
      <button class="button button-medium-filled button-rounded ">Medium info</button>
      <button class="button button-medium button-o-rounded">Medium info</button>
      <button class="button button-medium-filled button-o-rounded ">Medium info</button>
    </div>
```

**Comment by ivklgn** [comment]
в css нарушено форматирование. попробуйте разберитесь с автоформатированием css кода в редакторе

**Comment by ivklgn** [comment]
```css
.button{
  display: flexbox;
  flex-direction: column;
  padding: 5px;
  margin: 0 15px 15px 0;
  border: none; 
}
```

1. `display: flex;`
2. кнопка не должна быть flex-контейнером, потому что в ней нет дочерних элементов

**Comment by ivklgn** [comment]
```html
.button-large .filled{
  background:gray;
  border: solid;
  border-color: grey;
  border-width: 2px;
}
```

должно быть:

```html
.button-large.filled{
  background:gray;
  border: solid;
  border-color: grey;
  border-width: 2px;
}
```

откройте лекцию и посмотрите почему так должно быть :)

**Comment by ivklgn** [comment]
```css
.rounded{
  border-radius:5px;
  border:solid;
  border-width: 2px;
}
.oval{
  border-radius:20px;
  border:solid;
  border-width: 2px;

}
.filled{
  color: white;
}
.standart{
  border:solid;
  border-width: 2px;
}
```

данные классы не должны быть глобальными, а должны работать только с базовым классом .button:
пример:

```css
.button.standart {
  border:solid;
  border-width: 2px;
}
```
